MendersGame/front-end-cryptid-seeker

src/App.jsx

added useEffect Function in app.jsx

App jsx changes

---

src/pages/SightingList/SightingList.jsx

Sightings list

---

src/pages/NewSighting/NewSighting.jsx

New sighting

---

src/pages/EditSighting/EditSighting.jsx

Edit sighting

---

src/components/NewComment/NewComment.jsx

New comment form

---

src/components/CommentCard/CommentCard.jsx
src/components/Comments/Comments.jsx

add Comments and CommentCard components.

add comments and commentCard components

---

src/components/NewComment/NewComment.jsx
src/pages/SightingDetails/SightingDetails.jsx

Added import and section for comments on details page

Comments details

---

src/App.jsx
src/services/sightingService.js

Change routes

---

src/components/CryptidCard/CryptidCard.jsx
src/components/CryptidCard/CryptidCard.module.css
src/components/CryptidDescription/CryptidDescription.jsx
src/components/CryptidInfo/CryptidInfo.jsx

add details button on cryptid cards

Cryptid card feature

---

src/components/CryptidCard/CryptidCard.jsx
src/components/CryptidDescription/CryptidDescription.jsx
src/components/CryptidDescription/CryptidDescription.module.css

added image and region to cryptid card description

Add region prop

---

src/components/AuthorInfo/AuthorInfo.jsx
src/components/Reviews/Reviews.jsx

Reviews are Now being displayed

Reviews checking

---

src/components/CryptidCard/CryptidCard.module.css
src/components/CryptidDescription/CryptidDescription.module.css
src/components/CryptidInfo/CryptidInfo.module.css
src/components/EditComment/EditComment.module.css
src/pages/CryptidList/CryptidList.module.css

edit for cryptid cards styling

Card sizing edits

---

src/components/CryptidCard/CryptidCard.jsx
src/components/CryptidCard/CryptidCard.module.css
src/components/CryptidDescription/CryptidDescription.jsx
src/components/CryptidDescription/CryptidDescription.module.css
src/components/CryptidInfo/CryptidInfo.module.css
src/components/EditComment/EditComment.module.css

More styling changes for cryptid cards

More styling changes

---

src/pages/NewSighting/NewSighting.jsx
src/pages/NewSighting/NewSighting.module.css

start styling for new sighting page

start styling for new sighting page

---

src/components/AuthorInfo/AuthorInfo.jsx
src/components/AuthorInfo/AuthorInfo.module.css
src/components/DateCard/DateCard.jsx
src/components/DateCard/DateCard.module.css
src/components/SightingCard/SightingCard.jsx
src/components/SightingCard/SightingCard.module.css
src/pages/NewSighting/NewSighting.jsx
src/pages/NewSighting/NewSighting.module.css
src/pages/Profiles/Profiles.jsx
src/pages/Profiles/Profiles.module.css
src/pages/SightingDetails/SightingDetails.jsx
src/pages/SightingDetails/SightingDetails.module.css
src/pages/SightingList/SightingList.jsx
src/pages/SightingList/SightingList.module.css

Newsighting branch

---

src/components/AuthorInfo/AuthorInfo.jsx
src/components/AuthorInfo/AuthorInfo.module.css
src/components/NewComment/NewComment.jsx
src/components/NewComment/NewComment.module.css
src/pages/EditSighting/EditSighting.jsx
src/pages/EditSighting/EditSighting.module.css
src/pages/SightingDetails/SightingDetails.jsx
src/pages/SightingDetails/SightingDetails.module.css
src/pages/SightingList/SightingList.jsx
src/pages/SightingList/SightingList.module.css

styling changes for sighting details and author components

Styling changes part 2

---

src/components/AuthorInfo/AuthorInfo.jsx
src/components/CryptidSearch/CryptidSearch.jsx
src/components/Reviews/Reviews.jsx
src/pages/CryptidList/CryptidList.jsx

Added Search Bar to Cryptid Page

Search form

---

src/pages/EditSighting/EditSighting.jsx
src/pages/EditSighting/EditSighting.module.css
src/pages/SightingList/SightingList.jsx

styling changes for edit sighting page

Styling changes part 3

---

src/components/NavBar/NavBar.module.css
src/pages/EditSighting/EditSighting.jsx
src/pages/EditSighting/EditSighting.module.css
src/pages/SightingDetails/SightingDetails.jsx

fixed navbar and edit sightings page view

Newest styling

---

src/components/CryptidSearch/CryptidSearch.jsx
src/components/DateCard/DateCard.jsx
src/components/NavBar/NavBar.jsx
src/components/NewComment/NewComment.jsx
src/components/NewReview/NewReview.jsx
src/components/Reviews/Reviews.jsx
src/components/SightingCard/SightingCard.jsx
src/pages/ChangePassword/ChangePassword.jsx
src/pages/CryptidDetails/CryptidDetails.jsx
src/pages/CryptidList/CryptidList.jsx
src/pages/EditSighting/EditSighting.jsx
src/pages/Landing/Landing.jsx
src/pages/Login/Login.jsx
src/pages/NewSighting/NewSighting.jsx
src/pages/SightingDetails/SightingDetails.jsx
src/pages/SightingList/SightingList.jsx
src/services/cryptidService.js
src/services/sightingService.js

Some minor indentation and double quote replacements

Code clean2

---

src/components/SightingCard/SightingCard.module.css
src/pages/EditSighting/EditSighting.module.css
src/pages/SightingList/SightingList.module.css

fixed dissapearing border boxes. adding hover over sighting list cards

Navbar text size

---

src/components/SightingCard/SightingCard.module.css
src/pages/CryptidDetails/CryptidDetails.jsx
src/pages/CryptidDetails/CryptidDetails.module.css

CSS styling fixes on cryptid details page

 cryptid details page fixes

---

src/pages/EditComment/EditComment.jsx
src/pages/EditComment/EditComment.module.css
src/pages/EditReview/EditReview.jsx
src/pages/EditReview/EditReview.module.css

Edit comments

---

src/components/NewReview/NewReview.jsx
src/components/NewReview/NewReview.module.css
src/components/ReviewCard/ReviewCard.module.css
src/pages/CryptidDetails/CryptidDetails.module.css
src/pages/EditReview/EditReview.jsx
src/pages/EditReview/EditReview.module.css

finished edit reviews still working on reviews css

Reviewsedit css

---

src/pages/EditReview/EditReview.module.css
src/pages/EditSighting/EditSighting.module.css
src/pages/NewSighting/NewSighting.module.css

change color on form inputs

---

src/components/NewComment/NewComment.module.css
src/components/ReviewCard/ReviewCard.module.css
src/pages/CryptidDetails/CryptidDetails.module.css
src/pages/SightingDetails/SightingDetails.jsx
src/pages/SightingDetails/SightingDetails.module.css

comments fixed to look like reviews

fix comment bar

---

src/components/AuthorInfo/AuthorInfo.module.css
src/components/SightingCard/SightingCard.jsx
src/components/SightingCard/SightingCard.module.css

fix sighting card text and positioning

Fiximagesightinglist

---

src/components/CryptidCard/CryptidCard.module.css
src/components/CryptidDescription/CryptidDescription.jsx
src/components/CryptidDescription/CryptidDescription.module.css
src/components/CryptidInfo/CryptidInfo.module.css
src/pages/CryptidList/CryptidList.module.css

fix cryptid card cryptid name position

 change text name on cryptid card

---

README.md

 readme final fixes
